### ISSUE TITLE
Respect prefers-reduced-motion media query

### ISSUE THREAD

**Issue by jfrost-mo** [cylc/cylc-ui#1495]
### Problem

The cylc UI doesn't currently respect user agents setting [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion). This accessibility option indicates whether animations should play, and is useful to both people who get nauseous at too much animation, and to people on systems that don't have the graphics to run the animations smoothly. (E.g. VDIs at the Met Office)

### Proposed Solution

Fortunately you can just add a snippet of CSS to your pages to prevent animations. It reduces their duration to near-instant rather than removing them entirely, as some website rely on the events fired during an animation. I think this CSS just needs to be added to [src/styles/index.scss](https://github.com/cylc/cylc-ui/blob/master/src/styles/index.scss).

```css
/* Remove all animations, transitions and smooth scroll for people that prefer
not to see them. Based on https://web.dev/prefers-reduced-motion/ */
@media (prefers-reduced-motion: reduce) {
  html:focus-within {
    scroll-behavior: auto;
  }

  *,
  *::before,
  *::after {
    animation-delay: -1ms !important;
    animation-duration: 1ms !important;
    animation-iteration-count: 1 !important;
    background-attachment: initial !important;
    scroll-behavior: auto !important;
    transition-duration: 0s !important;
    transition-delay: 0s !important;
  }
}
```
